# Generated by Django 5.1.6 on 2025-05-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
