# Generated by Django 5.1.6 on 2025-05-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0002_alter_anime_description_alter_anime_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
