# Generated by Django 5.1.6 on 2025-05-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0003_alter_anime_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
    ]
