# Generated by Django 5.1.6 on 2025-05-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0004_rename_thumbnail_anime_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True),
        ),
    ]
